services:
  db:
    image: mongo:7.0.1
    container_name: fastAPIdb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: fast_api_db_data
        target: /data/db

volumes:
  fast_api_db_data:
