services:
  db:
    image: mongo:7.0.1
    container_name: fastAPIdb
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: fast_api_db_data
        target: /data/db
  api:
    image: fast-api_prodalike:1.0.0
    container_name: fast-api_prodalike
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    depends_on:
      - db
  server:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - type: bind
        read_only: true
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        read_only: true
        source: ./certs
        target: /etc/ssl/certs
    depends_on:
      - api

volumes:
  fast_api_db_data:
